on:
  release:
    types:
      - published

name: Build Rocket Plugin

env:
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  deploy:
    name: Build WP Rocket Plugin
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get latest release
        run: |
          # echo "UPSTREAM_RELEASE=$(curl -f -sSL "https://api.github.com/repos/wp-media/wp-rocket/releases/latest" 2>/dev/null|awk -F'"' '/tag_name/{print $4}')" >> $GITHUB_ENV
          echo "UPSTREAM_RELEASE=$(curl -f -sSL "https://api.github.com/repos/wp-media/wp-rocket/releases/latest" 2>/dev/null|awk -F'"' '/"name":/{print $4}')" >> $GITHUB_ENV

      - name: Check upstream release
        if: ! ${{ env.UPSTREAM_RELEASE }}
        run: { echo "__ERROR: FAILED get '${UPSTREAM_RELEASE}' release"; exit 2; }

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-


      - name: Download zip
        if: ${{ env.UPSTREAM_RELEASE }} && !cancelled()
        run: |
          wget -O base.zip "https://github.com/wp-media/wp-rocket/archive/v${UPSTREAM_RELEASE}.zip"
          unzip base.zip
          mv wp-rocket-* wp-rocket
        working-directory: /tmp

      - name: Remove unmet dependencies by legacy versions
        run: composer remove --dev --update-no-dev --no-scripts coenjacobs/mozart
        working-directory: /tmp/wp-rocket

      - name: Run composer
        run: composer install --no-scripts --no-dev
        working-directory: /tmp/wp-rocket

      - name: Remove composer installers
        run: composer remove composer/installers --update-no-dev --no-scripts
        working-directory: /tmp/wp-rocket

      - name: Optimize autoloader
        run: composer dumpautoload -o
        working-directory: /tmp/wp-rocket

      - name: Zip Folder
        run: |
          zip -r wp-rocket-${UPSTREAM_RELEASE}.zip wp-rocket
          find /tmp -type f -iname '*.zip' | xargs ls -lh
        working-directory: /tmp

      # - name: Install Swift
      #   run: |
      #     sudo apt update
      #     sudo apt install python3-swiftclient -y
      # # Use Openstack Swift to upload the zip to OVH block storage
      # # We post a header to instruct the file to be deleted after 10 minutes
      # - name: Upload Zip
      #   env:
      #     OS_AUTH_URL: ${{ secrets.OBJECT_STORAGE_URL }}
      #     OS_PASSWORD: ${{ secrets.OBJECT_STORAGE_PASSWORD }}
      #     OS_PROJECT_NAME: ${{ secrets.OBJECT_STORAGE_PROJECT }}
      #     OS_PROJECT_ID: ${{ secrets.OBJECT_STORAGE_PROJECT_ID }}
      #     OS_REGION_NAME: ${{ secrets.OBJECT_STORAGE_REGION }}
      #     OS_USERNAME: ${{ secrets.OBJECT_STORAGE_USERNAME }}
      #     OS_USER_DOMAIN_NAME: "Default"
      #   working-directory: /tmp
      #   run: |
      #     /usr/bin/swift upload rocket-plugin __wp-rocket_${GITHUB_REF##*v}.zip
      #     /usr/bin/swift post --header "X-Delete-After: 600" rocket-plugin __wp-rocket_${GITHUB_REF##*v}.zip
      # # Call the webhook on AWX to fetch and deploy the zip
      # - name: Invoke deployment hook
      #   uses: distributhor/workflow-webhook@v1
      #   env:
      #     webhook_type: 'json-extended'
      #     webhook_url: ${{ secrets.WEBHOOK_URL_PLUGIN }}
      #     webhook_secret: ${{ secrets.WEBHOOK_KEY_PLUGIN }}

      - name: Generate release tag
        id: tag
        if: env.UPLOADLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "::set-output name=release_tag::${UPSTREAM_RELEASE}"
          echo "::set-output name=release_date::$(date +'%F')"
          touch release.txt
          echo -e "\nbuild [wp-rocket-${UPSTREAM_RELEASE}](https://github.com/wp-media/wp-rocket/releases) release" >> release.txt
          echo "::set-output name=status::success"

      - name: Upload build to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          name: "${{ steps.tag.outputs.release_date }} wp-rocket ${UPSTREAM_RELEASE}"
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: /tmp/wp-rocket-${{ env.UPSTREAM_RELEASE }}.zip


